name: Deploy to Elastic Beanstalk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the application
      run: dotnet build --configuration Release

    - name: Publish the application
      run: dotnet publish --configuration Release --output ./publish

    - name: Zip the published application
      run: |
        cd ./publish
        zip -r ../app.zip .

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-north-1'

    - name: Upload the application to S3
      run: |
        aws s3 cp ./app.zip s3://elasticbeanstalk-eu-north-1-338593158495/app.zip

    - name: Create the application version in Elastic Beanstalk
      id: create_version
      run: |
        VERSION_LABEL=$(date +%Y%m%d%H%M%S)
        aws elasticbeanstalk create-application-version \
          --application-name groupflow-backend \
          --version-label $VERSION_LABEL \
          --source-bundle S3Bucket="elasticbeanstalk-eu-north-1-338593158495",S3Key="app.zip"
        echo "VERSION_LABEL=$VERSION_LABEL" >> $GITHUB_ENV

    - name: Deploy to Elastic Beanstalk
      run: |
        VERSION_LABEL=$VERSION_LABEL
        aws elasticbeanstalk update-environment \
          --application-name groupflow-backend \
          --environment-name groupflow-backend-env \
          --version-label $VERSION_LABEL
